apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: kpack-dependencies.community.tanzu.vmware.com.0.0.20
spec:
  refName: kpack-dependencies.community.tanzu.vmware.com
  version: 0.0.20
  capacityRequirementsDescription: Registry with > 1GB available space
  releaseNotes: https://github.com/vmware-tanzu/package-for-kpack-dependencies/releases/tag/v0.0.20
  valuesSchema:
    openAPIv3:
      title: kpack-dependencies.community.tanzu.vmware.com values schema
      properties:
        kp_default_repository:
          type: string
          description: Docker repository for builder images. The same value used during installation of kpack.
          examples:
          - registry.io/kpack
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: projects.registry.vmware.com/kpack/dependencies@sha256:3a627c1b560b371a49fae0e2f3430095236b01a3ec0c7323312da73f451c32c9
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
